spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Rootroot@1045
    url: jdbc:mysql://localhost:3307/Namhimjwt

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwt:
    secret: securesecuresecuresecuresecuresecure